//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoMayToChucDb : DbContext
    {
        public BoMayToChucDb()
            : base("name=BoMayToChucDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoNhiem> BoNhiems { get; set; }
        public virtual DbSet<CanBoThuocNhomNguoiDung> CanBoThuocNhomNguoiDungs { get; set; }
        public virtual DbSet<ChucNangNguoiDung> ChucNangNguoiDungs { get; set; }
        public virtual DbSet<ChucNangThuocNhomNguoiDung> ChucNangThuocNhomNguoiDungs { get; set; }
        public virtual DbSet<ChucNangUngDung> ChucNangUngDungs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<CoQuan> CoQuans { get; set; }
        public virtual DbSet<HoSoCanBo> HoSoCanBoes { get; set; }
        public virtual DbSet<NhomNguoiDung> NhomNguoiDungs { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<UngDung_CoQuan> UngDung_CoQuan { get; set; }
        public virtual DbSet<NhatKy> NhatKies { get; set; }
    }
}
