//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoNhiem
    {
        public int BoNhiemId { get; set; }
        public Nullable<int> CoQuanId { get; set; }
        public Nullable<int> PhongBanId { get; set; }
        public Nullable<int> ChucVuId { get; set; }
        public Nullable<int> CanBoId { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<bool> LoaiHinhChucVu { get; set; }
        public Nullable<bool> ConHieuLuc { get; set; }
        public Nullable<bool> ConHoatDong { get; set; }
        public string QuyetDinhBoNhiem { get; set; }
        public string MoTaCongViec { get; set; }
    }
}
