//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanBoThuocNhomNguoiDung
    {
        public int CanBoThuocNhomNguoiDungId { get; set; }
        public Nullable<int> NhomNguoiDungId { get; set; }
        public Nullable<int> CanBoId { get; set; }
    }
}
