//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNangNguoiDung
    {
        public int ChucNangNguoiDungId { get; set; }
        public Nullable<int> CanBoId { get; set; }
        public Nullable<int> CoQuanId { get; set; }
        public int ChucNangId { get; set; }
        public string MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public Nullable<int> NhomNguoiDungId { get; set; }
        public string MaUngDung { get; set; }
    }
}
