//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public int ChucVuId { get; set; }
        public string MaChucVu { get; set; }
        public string TenChucVu { get; set; }
        public Nullable<int> ThuTuUuTien { get; set; }
        public Nullable<bool> ConHoatDong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> CanBoTaoId { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<int> CanBoXoaId { get; set; }
    }
}
