//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNangUngDung
    {
        public int ChucNangId { get; set; }
        public string MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public Nullable<int> ThuocChucNangId { get; set; }
        public Nullable<int> ThuTuUuTien { get; set; }
        public string MaUngDung { get; set; }
        public string TenUngDung { get; set; }
        public Nullable<bool> ConHoatDong { get; set; }
    }
}
