//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoCanBo
    {
        public int CanBoId { get; set; }
        public string MaCanBo { get; set; }
        public string HoVaTen { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string SoCMND { get; set; }
        public string SoTheCanCuoc { get; set; }
        public Nullable<int> ThuTuUuTien { get; set; }
        public Nullable<int> CoQuanHienTaiId { get; set; }
        public Nullable<int> PhongBanHienTaiId { get; set; }
        public Nullable<int> ChucVuHienTaiId { get; set; }
        public Nullable<int> TrangThaiHoatDong { get; set; }
        public Nullable<int> LoaiTaiKhoan { get; set; }
        public Nullable<bool> ConHoatDong { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<int> CanBoXoaId { get; set; }
        public string AnhDaiDien { get; set; }
    }
}
