//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tavi.BoMayToChuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKy
    {
        public int NhatKyId { get; set; }
        public Nullable<int> CanBoTaoId { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CongViec { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> CoQuanId { get; set; }
        public string MaUngDung { get; set; }
    }
}
